# Generated by Django 5.0.2 on 2024-03-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField(max_length=200)),
                ("github", models.URLField()),
                ("image", models.FileField(blank=True, upload_to="media/")),
                ("show", models.BooleanField(default=False)),
            ],
        ),
    ]
