# Generated by Django 5.0.2 on 2024-03-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_projectinfo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinfo",
            name="image",
            field=models.FileField(blank=True, upload_to="media/"),
        ),
    ]
